name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          npm install
          npm run make
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 4bookmark-application
          path: out/make/zip/darwin/arm64/4Bookmark-darwin-arm64-1.0.0.zip
